services:
  db:
    container_name: pgroll
    image: postgres:18.4-bookworm
    environment:
      POSTGRES_DB: pgroll
      POSTGRES_USER: pgrolluser
      POSTGRES_PASSWORD: pgrollpassword
      PGDATA: /data/postgres
    volumes:
      - ./data/db:/data/postgres
    network_mode: host
